module.exports = {
    STATUS_NEW: "NEW",
    STATUS_IN_PROGRESS: "IN_PROGRESS",
    STATUS_COMPLETED: "COMPLETED",
    STATUS_ARCHIVED: "ARCHIVED",

    USER_ROLES_ADMIN: "ADMIN",
    USER_ROLES_EMPLOYEE: "EMPLOYEE"
}